name: Surveillance Notes
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: "3.9" }
      - name: Install
        run: |
          pip install playwright requests
          playwright install chromium
      - name: Run
        env:
          INSA_USER: ${{ secrets.INSA_USER }}
          INSA_PWD: ${{ secrets.INSA_PWD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python insa_bot.py
      - name: Save Cache
        run: |
          git config --global user.name "InsaBot"
          git config --global user.email "bot@insa.fr"
          git add notes.json
          git commit -m "MAJ Cache Notes" || exit 0
          git push
