name: Surveillance Notes
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with: { python-version: "3.9" }

      - name: Install Dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Run Bot
        env:
          INSA_USER: ${{ secrets.INSA_USER }}
          INSA_PWD: ${{ secrets.INSA_PWD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python insa_bot.py

      - name: Save Cache
        run: |
          git config --global user.name "InsaBot"
          git config --global user.email "bot@insa.fr"
          # On s'assure que le fichier existe avant l'ajout
          touch notes.json
          git add notes.json
          # Commit et Push seulement s'il y a une modification
          if ! git diff --cached --quiet; then
            git commit -m "MAJ Cache Notes [skip ci]"
            git push
          else
            echo "Aucun changement Ã  sauvegarder."
          fi
